require("caolancode.lazy")
require("caolancode.core.keymaps")
require("caolancode.core.options")
require("caolancode.plugins.treesitter")
require("caolancode.plugins.telescope")
require("caolancode.plugins.lualine")
